version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ezo_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: